In [18]:
import pandas as pd
import numpy as np
import tensorflow as ts
import os
from sklearn.preprocessing import MinMaxScaler

In [19]:
dataset = os.path.join('datasets', 'cardio_train.csv')
df = pd.read_csv(dataset)
df

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69995,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [20]:
df.isna().sum()

age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [21]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [22]:
mms = MinMaxScaler()
X = mms.fit_transform(X)
X

array([[0.58807588, 1.        , 0.57948718, ..., 0.        , 0.        ,
        1.        ],
       [0.73015873, 0.        , 0.51794872, ..., 0.        , 0.        ,
        1.        ],
       [0.6240031 , 0.        , 0.56410256, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.64018583, 1.        , 0.65641026, ..., 0.        , 1.        ,
        0.        ],
       [0.90073558, 0.        , 0.55384615, ..., 0.        , 0.        ,
        0.        ],
       [0.75431669, 0.        , 0.58974359, ..., 0.        , 0.        ,
        1.        ]], shape=(70000, 11))

In [23]:
np.shape(X)

(70000, 11)

In [24]:
y = pd.get_dummies(y)
y

           0      1
0       True  False
1      False   True
2      False   True
3      False   True
4       True  False
...      ...    ...
69995   True  False
69996  False   True
69997  False   True
69998  False   True
69999   True  False

[70000 rows x 2 columns]