In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import os

It's not the real data

In [3]:
dataset = os.path.join("datasets", "EPA_fuel_economy_summary.csv")
df = pd.read_csv(dataset)
df

,make,model,year,transmission,drive,date_range,fuel_type_summary,class_summary,cylinders,displ,co2,barrels08,fuelCost08,comb08,highway08,city08
0,Acura,NSX,2000,Automatic,2WD,2000-2010,Gas,Car,6.0,3.0,-1,16.528333,3250,18,22,15
1,Acura,NSX,2000,Manual,2WD,2000-2010,Gas,Car,6.0,3.2,-1,16.528333,3250,18,22,15
2,BMW,M Coupe,2000,Manual,2WD,2000-2010,Gas,Car,6.0,3.2,-1,15.658421,3050,19,23,17
3,BMW,Z3 Coupe,2000,Automatic,2WD,2000-2010,Gas,Car,6.0,2.8,-1,15.658421,3050,19,24,17
4,BMW,Z3 Coupe,2000,Manual,2WD,2000-2010,Gas,Car,6.0,2.8,-1,15.658421,3050,19,24,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23980,Rolls-Royce,Wraith Black Badge,2020,Automatic,2WD,2011-2020,Gas,Car,12.0,6.6,624,21.250714,4150,14,18,12
23981,Rolls-Royce,Ghost Black Badge,2020,Automatic,2WD,2011-2020,Gas,Car,12.0,6.6,637,21.250714,4150,14,18,12
23982,Roush Performance,F150 Pickup 4WD,2020,Automatic,4WD,2011-2020,Gas,Truck,8.0,5.0,696,22.885385,4500,13,16,11
23983,Koenigsegg,Regera,2019,Automatic,2WD,2011-2020,Gas,Car,8.0,5.0,610,27.046364,5300,11,11,11
23984,Koenigsegg,Regera,2020,Automatic,2WD,2011-2020,Gas,Car,8.0,5.0,610,27.046364,5300,11,11,11

In [4]:
fig = px.histogram(df, x='fuelCost08')
fig.show()

In [5]:
fig = px.histogram(
    df,
    x='fuelCost08',
    color='class_summary',
    labels={'fuelCost08': 'Annual Fuel Cost'},
    nbins=40,
    title='Fuel Cost Distribution'
)
fig.show()

In [6]:
fig = px.histogram(
    df,
    x='fuelCost08',
    color='class_summary',
    labels={'fuelCost08': 'Annual Fuel Cost'},
    nbins=40,
    template='seaborn',
    title='Fuel Cost Distribution'
)
fig.show()

In [7]:
fig = px.colors.qualitative.swatches()
fig.show()

In [8]:
fig = px.histogram(
    df,
    x='fuelCost08',
    color='class_summary',
    labels={'fuelCost08': 'Annual Fuel Cost'},
    nbins=40,
    title='Fuel Cost Distribution',
    color_discrete_sequence=px.colors.qualitative.Set2
)
fig.show()

In [9]:
fig = px.colors.sequential.swatches()
fig.show()

In [10]:
fig = px.box(
    df,
    x='fuelCost08',
    y='class_summary',
    color='class_summary',
    labels={'fuelCost08': 'fuel cost'}
)
fig.update_layout(showlegend=False)
fig.show()

In [11]:
fig = px.strip(
    df,
    x='fuelCost08',
    y='class_summary',
    color='class_summary',
    labels={'fuelCost08': 'fuel cost'}
)
fig.update_layout(showlegend=False)
fig.show()

In [12]:
avg_cost = round(df['fuelCost08'].mean(),2)
fig = px.histogram(
    df,
    x='fuelCost08',
    color='class_summary',
    nbins=40,
    title='Fuel Cost Distribution',
    color_discrete_sequence=px.colors.qualitative.G10
)
fig.update_yaxes(title_text='Number of Cars')
fig.add_vline(x=avg_cost, annotation_text=f'Average ${avg_cost}')
fig.show()

In [13]:
fig = px.histogram(
    df,
    x='fuelCost08',
    color='class_summary',
    nbins=40,
    title='Fuel Cost Distribution',
    marginal='box',
    color_discrete_sequence=px.colors.qualitative.Bold
)
fig.show()

In [14]:
fig = px.scatter(
    df.query('co2 > 0'),
    x='fuelCost08',
    y='co2',
    hover_name='model',
    size='cylinders',
    color='cylinders',
    hover_data=['make', 'year', 'cylinders']
)
fig.show()

In [15]:
fig = px.scatter(
    df.query('co2 > 0'),
    x='fuelCost08',
    y='co2',
    hover_name='model',
    size='cylinders',
    color='cylinders',
    hover_data={'make': True, 'year': True, 'cylinders': ':.0f', 'fuelCost08': ':$.0f'}
)
fig.show()

In [16]:
fig = px.scatter_matrix(
    df,
    dimensions=['cylinders', 'fuelCost08'],
    color='make'
)
fig.show()

In [19]:
avg_by_year = df.groupby(['year'], as_index=False).agg({'fuelCost08': 'mean'}).round(2)
avg_by_year

    year  fuelCost08
0   2000     2620.04
1   2001     2645.31
2   2002     2673.95
3   2003     2730.11
4   2004     2724.78
5   2005     2736.02
6   2006     2752.85
7   2007     2751.78
8   2008     2761.89
9   2009     2621.76
10  2010     2547.11
11  2011     2539.35
12  2012     2504.96
13  2013     2431.43
14  2014     2428.15
15  2015     2376.03
16  2016     2332.09
17  2017     2331.87
18  2018     2343.58
19  2019     2351.49
20  2020     2391.74

In [22]:
fig = px.scatter(avg_by_year, x='year', y='fuelCost08', trendline='ols')
fig.show()

In [23]:
fig = px.scatter(avg_by_year, x='year', y='fuelCost08', trendline='lowess')
fig.show()

In [25]:
fig = px.sunburst(
    df.query('year > 2015'),
    path=['year', 'class_summary']
)
fig.show()

In [27]:
fig = px.density_heatmap(df, x='year', y='class_summary')
fig.show()

In [28]:
fig = px.density_heatmap(
    df,
    x='year', 
    y='highway08',
    marginal_y='histogram',
    template='plotly_white',
    range_y=[10, 40]
)
fig.show()

In [29]:
fig = px.box(
    df,
    x='date_range',
    y='fuelCost08',
    facet_col='fuel_type_summary',
    facet_col_wrap=2,
    boxmode='group',
    color='drive',
    points=False,
    height=700
)
fig.show()

In [31]:
fig = px.histogram(
    df,
    x='fuelCost08',
    facet_col='class_summary',
    facet_col_wrap=4,
    nbins=40
)
fig.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))
fig.show()

In [38]:
fig = px.strip(
    df,
    x='fuelCost08',
    y='class_summary',
    color='class_summary',
    range_x=[300, 4000],
)
fig.update_layout(showlegend=False)
fig.update_yaxes(title='Vehicle Class')
fig.update_xaxes(title='Estimated Fuel Cost')
fig.add_annotation(
    x=1400,
    y='Van',
    text='Outlier Value',
    showarrow=True,
    arrowhead=1
)
fig.add_vrect(
    x0=3500,
    x1=4000,
    fillcolor='LightSalmon',
    opacity=0.5,
    layer='below',
    line_width=0,
    annotation_text='Inefficient Vehicles',
    annotation_position='bottom'
)

fig.show()