In [11]:
import random
import pandas as pd
import os
import re

In [2]:
n = 216930
s = 1000
skip = [0].append(sorted(random.sample(range(n), n-s)))

In [3]:
dataset = os.path.join('..','..', '..', 'datasets', 'JEOPARDY_CSV.csv')
df = pd.read_csv(dataset, skiprows=lambda i: i>0 and random.random() > 0.02)
df

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,5957,2010-07-06,Final Jeopardy!,HISTORIC WOMEN,NaN,She was born in Virginia around 1596 & died in...,Pocahontas
1,3751,2000-12-18,Jeopardy!,TRAVEL & TOURISM,$300,We're not stringing you along: this capital of...,Prague
2,4931,2006-02-06,Double Jeopardy!,FROM THE GREEK,$1600,"(<a href=""http://www.j-archive.com/media/2006-...",a palindrome
3,4931,2006-02-06,Double Jeopardy!,FROM THE GREEK,$2000,It's an outline of the contents of a course or...,a syllabus
4,5690,2009-05-08,Double Jeopardy!,ANATOMY,$1200,The talus fits between the ends of these 2 bon...,the tibia & fibula
...,...,...,...,...,...,...,...
4450,4999,2006-05-11,Jeopardy!,THE NEW YORK TIMES BUSINESS,$200,"Union Pacific, HP & this Atlanta-based beverag...",Coca-Cola
4451,4999,2006-05-11,Jeopardy!,SCIENCE BRIEFS,$600,"Conceived around 1686, ""G"" is known as this ma...",Newton
4452,4999,2006-05-11,Jeopardy!,"RATED ""R""",$800,Sculptor Constantin Brancusi was born in this ...,Romania
4453,4999,2006-05-11,Jeopardy!,THE NEW YORK TIMES BUSINESS,$1000,"A Times writer's ""Scandalot"" featured Maurice ...",AIG
4454,4999,2006-05-11,Double Jeopardy!,OFF-BROADWAY,$2000,In 2006 the cast of this long-running hit emba...,Stomp

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4455 entries, 0 to 4454
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Show Number  4455 non-null   int64
 1    Air Date    4455 non-null   object
 2    Round       4455 non-null   object
 3    Category    4455 non-null   object
 4    Value       4367 non-null   object
 5    Question    4455 non-null   object
 6    Answer      4455 non-null   object
dtypes: int64(1), object(6)
memory usage: 243.8+ KB

In [6]:
X = df[[' Question']]
X

                                               Question
0     She was born in Virginia around 1596 & died in...
1     We're not stringing you along: this capital of...
2     (<a href="http://www.j-archive.com/media/2006-...
3     It's an outline of the contents of a course or...
4     The talus fits between the ends of these 2 bon...
...                                                 ...
4450  Union Pacific, HP & this Atlanta-based beverag...
4451  Conceived around 1686, "G" is known as this ma...
4452  Sculptor Constantin Brancusi was born in this ...
4453  A Times writer's "Scandalot" featured Maurice ...
4454  In 2006 the cast of this long-running hit emba...

[4455 rows x 1 columns]

In [10]:
with open("stopwords.txt", encoding="utf8") as stopword_file:
    stopwords = stopword_file.readlines()

stopwords = [line.replace("\n", "") for line in stopwords]
stopwords

["'ll",
 "'tis",
 "'twas",
 "'ve",
 '10',
 '39',
 'a',
 "a's",
 'able',
 'ableabout',
 'about',
 'above',
 'abroad',
 'abst',
 'accordance',
 'according',
 'accordingly',
 'across',
 'act',
 'actually',
 'ad',
 'added',
 'adj',
 'adopted',
 'ae',
 'af',
 'affected',
 'affecting',
 'affects',
 'after',
 'afterwards',
 'ag',
 'again',
 'against',
 'ago',
 'ah',
 'ahead',
 'ai',
 "ain't",
 'aint',
 'al',
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'alongside',
 'already',
 'also',
 'although',
 'always',
 'am',
 'amid',
 'amidst',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'announce',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'ao',
 'apart',
 'apparently',
 'appear',
 'appreciate',
 'appropriate',
 'approximately',
 'aq',
 'ar',
 'are',
 'area',
 'areas',
 'aren',
 "aren't",
 'arent',
 'arise',
 'around',
 'arpa',
 'as',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'associated',
 'at',
 'au',
 'auth',
 'available',
 'aw',
 'away',
 'awfully',
 'az',
 'b',
 'ba',
 'back',
 'backed',
 'backing',
 'backs',
 'backward',
 'backwards',
 'bb',
 'bd',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'began',
 'begin',
 'beginning',
 'beginnings',
 'begins',
 'behind',
 'being',
 'beings',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'bf',
 'bg',
 'bh',
 'bi',
 'big',
 'bill',
 'billion',
 'biol',
 'bj',
 'bm',
 'bn',
 'bo',
 'both',
 'bottom',
 'br',
 'brief',
 'briefly',
 'bs',
 'bt',
 'but',
 'buy',
 'bv',
 'bw',
 'by',
 'bz',
 'c',
 "c'mon",
 "c's",
 'ca',
 'call',
 'came',
 'can',
 "can't",
 'cannot',
 'cant',
 'caption',
 'case',
 'cases',
 'cause',
 'causes',
 'cc',
 'cd',
 'certain',
 'certainly',
 'cf',
 'cg',
 'ch',
 'changes',
 'ci',
 'ck',
 'cl',
 'clear',
 'clearly',
 'click',
 'cm',
 'cmon',
 'cn',
 'co',
 'co.',
 'com',
 'come',
 'comes',
 'computer',
 'con',
 'concerning',
 'consequently',
 'consider',
 'considering',
 'contain',
 'containing',
 'contains',
 'copy',
 'corresponding',
 'could',
 "could've",
 'couldn',
 "couldn't",
 'couldnt',
 'course',
 'cr',
 'cry',
 'cs',
 'cu',
 'currently',
 'cv',
 'cx',
 'cy',
 'cz',
 'd',
 'dare',
 "daren't",
 'darent',
 'date',
 'de',
 'dear',
 'definitely',
 'describe',
 'described',
 'despite',
 'detail',
 'did',
 'didn',
 "didn't",
 'didnt',
 'differ',
 'different',
 'differently',
 'directly',
 'dj',
 'dk',
 'dm',
 'do',
 'does',
 'doesn',
 "doesn't",
 'doesnt',
 'doing',
 'don',
 "don't",
 'done',
 'dont',
 'doubtful',
 'down',
 'downed',
 'downing',
 'downs',
 'downwards',
 'due',
 'during',
 'dz',
 'e',
 'each',
 'early',
 'ec',
 'ed',
 'edu',
 'ee',
 'effect',
 'eg',
 'eh',
 'eight',
 'eighty',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'end',
 'ended',
 'ending',
 'ends',
 'enough',
 'entirely',
 'er',
 'es',
 'especially',
 'et',
 'et-al',
 'etc',
 'even',
 'evenly',
 'ever',
 'evermore',
 'every',
 'everybody',
 'everyone',
 'everything',
 'everywhere',
 'ex',
 'exactly',
 'example',
 'except',
 'f',
 'face',
 'faces',
 'fact',
 'facts',
 'fairly',
 'far',
 'farther',
 'felt',
 'few',
 'fewer',
 'ff',
 'fi',
 'fifteen',
 'fifth',
 'fifty',
 'fify',
 'fill',
 'find',
 'finds',
 'fire',
 'first',
 'five',
 'fix',
 'fj',
 'fk',
 'fm',
 'fo',
 'followed',
 'following',
 'follows',
 'for',
 'forever',
 'former',
 'formerly',
 'forth',
 'forty',
 'forward',
 'found',
 'four',
 'fr',
 'free',
 'from',
 'front',
 'full',
 'fully',
 'further',
 'furthered',
 'furthering',
 'furthermore',
 'furthers',
 'fx',
 'g',
 'ga',
 'gave',
 'gb',
 'gd',
 'ge',
 'general',
 'generally',
 'get',
 'gets',
 'getting',
 'gf',
 'gg',
 'gh',
 'gi',
 'give',
 'given',
 'gives',
 'giving',
 'gl',
 'gm',
 'gmt',
 'gn',
 'go',
 'goes',
 'going',
 'gone',
 'good',
 'goods',
 'got',
 'gotten',
 'gov',
 'gp',
 'gq',
 'gr',
 'great',
 'greater',
 'greatest',
 'greetings',
 'group',
 'grouped',
 'grouping',
 'groups',
 'gs',
 'gt',
 'gu',
 'gw',
 'gy',
 'h',
 'had',
 "hadn't",
 'hadnt',
 'half',
 'happens',
 'hardly',
 'has',
 'hasn',
 "hasn't",
 'hasnt',
 'have',
 'haven',
 "haven't",
 'havent',
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'hed',
 'hell',
 'hello',
 'help',
 'hence',
 'her',
 'here',
 "here's",
 'hereafter',
 'hereby',
 'herein',
 'heres',
 'hereupon',
 'hers',
 'herself',
 'herse”',
 'hes',
 'hi',
 'hid',
 'high',
 'higher',
 'highest',
 'him',
 'himself',
 'himse”',
 'his',
 'hither',
 'hk',
 'hm',
 'hn',
 'home',
 'homepage',
 'hopefully',
 'how',
 "how'd",
 "how'll",
 "how's",
 'howbeit',
 'however',
 'hr',
 'ht',
 'htm',
 'html',
 'http',
 'hu',
 'hundred',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'i.e.',
 'id',
 'ie',
 'if',
 'ignored',
 'ii',
 'il',
 'ill',
 'im',
 'immediate',
 'immediately',
 'importance',
 'important',
 'in',
 'inasmuch',
 'inc',
 'inc.',
 'indeed',
 'index',
 'indicate',
 'indicated',
 'indicates',
 'information',
 'inner',
 'inside',
 'insofar',
 'instead',
 'int',
 'interest',
 'interested',
 'interesting',
 'interests',
 'into',
 'invention',
 'inward',
 'io',
 'iq',
 'ir',
 'is',
 'isn',
 "isn't",
 'isnt',
 'it',
 "it'd",
 "it'll",
 "it's",
 'itd',
 'itll',
 'its',
 'itself',
 'itse”',
 'ive',
 'j',
 'je',
 'jm',
 'jo',
 'join',
 'jp',
 'just',
 'k',
 'ke',
 'keep',
 'keeps',
 'kept',
 'keys',
 'kg',
 'kh',
 'ki',
 'kind',
 'km',
 'kn',
 'knew',
 'know',
 'known',
 'knows',
 'kp',
 'kr',
 'kw',
 'ky',
 'kz',
 'l',
 'la',
 'large',
 'largely',
 'last',
 'lately',
 'later',
 'latest',
 'latter',
 'latterly',
 'lb',
 'lc',
 'least',
 'length',
 'less',
 'lest',
 'let',
 "let's",
 'lets',
 'li',
 'like',
 'liked',
 'likely',
 'likewise',
 'line',
 'little',
 'lk',
 'll',
 'long',
 'longer',
 'longest',
 'look',
 'looking',
 'looks',
 'low',
 'lower',
 'lr',
 'ls',
 'lt',
 'ltd',
 'lu',
 'lv',
 'ly',
 'm',
 'ma',
 'made',
 'mainly',
 'make',
 'makes',
 'making',
 'man',
 'many',
 'may',
 'maybe',
 "mayn't",
 'maynt',
 'mc',
 'md',
 'me',
 'mean',
 'means',
 'meantime',
 'meanwhile',
 'member',
 'members',
 'men',
 'merely',
 'mg',
 'mh',
 'microsoft',
 'might',
 "might've",
 "mightn't",
 'mightnt',
 'mil',
 'mill',
 'million',
 'mine',
 'minus',
 'miss',
 'mk',
 'ml',
 'mm',
 'mn',
 'mo',
 'more',
 'moreover',
 'most',
 'mostly',
 'move',
 'mp',
 'mq',
 'mr',
 'mrs',
 'ms',
 'msie',
 'mt',
 'mu',
 'much',
 'mug',
 'must',
 "must've",
 "mustn't",
 'mustnt',
 'mv',
 'mw',
 'mx',
 'my',
 'myself',
 'myse”',
 'mz',
 'n',
 'na',
 'name',
 'namely',
 'nay',
 'nc',
 'nd',
 'ne',
 'near',
 'nearly',
 'necessarily',
 'necessary',
 'need',
 'needed',
 'needing',
 "needn't",
 'neednt',
 'needs',
 'neither',
 'net',
 'netscape',
 'never',
 'neverf',
 'neverless',
 'nevertheless',
 'new',
 'newer',
 'newest',
 'next',
 'nf',
 'ng',
 'ni',
 'nine',
 'ninety',
 'nl',
 'no',
 'no-one',
 'nobody',
 'non',
 'none',
 'nonetheless',
 'noone',
 'nor',
 'normally',
 'nos',
 'not',
 'noted',
 'nothing',
 'notwithstanding',
 'novel',
 'now',
 'nowhere',
 'np',
 'nr',
 'nu',
 'null',
 'number',
 'numbers',
 'nz',
 'o',
 'obtain',
 'obtained',
 'obviously',
 'of',
 'off',
 'often',
 'oh',
 'ok',
 'okay',
 'old',
 'older',
 'oldest',
 'om',
 'omitted',
 'on',
 'once',
 'one',
 "one's",
 'ones',
 'only',
 'onto',
 'open',
 'opened',
 'opening',
 'opens',
 'opposite',
 'or',
 'ord',
 'order',
 'ordered',
 'ordering',
 'orders',
 'org',
 'other',
 'others',
 'otherwise',
 'ought',
 "oughtn't",
 'oughtnt',
 'our',
 'ours',
 'ourselves',
 'out',
 'outside',
 'over',
 'overall',
 'owing',
 'own',
 'p',
 'pa',
 'page',
 'pages',
 'part',
 'parted',
 'particular',
 'particularly',
 'parting',
 'parts',
 'past',
 'pe',
 'per',
 'perhaps',
 'pf',
 'pg',
 'ph',
 'pk',
 'pl',
 'place',
 'placed',
 'places',
 'please',
 'plus',
 'pm',
 'pmid',
 'pn',
 'point',
 'pointed',
 'pointing',
 'points',
 'poorly',
 'possible',
 'possibly',
 'potentially',
 'pp',
 'pr',
 'predominantly',
 'present',
 'presented',
 'presenting',
 'presents',
 'presumably',
 'previously',
 'primarily',
 'probably',
 'problem',
 'problems',
 'promptly',
 'proud',
 'provided',
 'provides',
 'pt',
 'put',
 'puts',
 'pw',
 'py',
 'q',
 'qa',
 'que',
 'quickly',
 'quite',
 'qv',
 'r',
 'ran',
 'rather',
 'rd',
 're',
 'readily',
 'really',
 'reasonably',
 'recent',
 'recently',
 'ref',
 'refs',
 'regarding',
 'regardless',
 'regards',
 'related',
 'relatively',
 'research',
 'reserved',
 'respectively',
 'resulted',
 'resulting',
 'results',
 'right',
 'ring',
 'ro',
 'room',
 'rooms',
 'round',
 'ru',
 'run',
 'rw',
 's',
 'sa',
 'said',
 'same',
 'saw',
 'say',
 'saying',
 'says',
 'sb',
 'sc',
 'sd',
 'se',
 'sec',
 'second',
 'secondly',
 'seconds',
 'section',
 'see',
 'seeing',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'seen',
 'sees',
 'self',
 'selves',
 'sensible',
 'sent',
 'serious',
 'seriously',
 'seven',
 'seventy',
 'several',
 'sg',
 'sh',
 'shall',
 "shan't",
 'shant',
 'she',
 "she'd",
 "she'll",
 "she's",
 'shed',
 'shell',
 'shes',
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'shouldnt',
 'show',
 'showed',
 'showing',
 'shown',
 'showns',
 'shows',
 'si',
 'side',
 'sides',
 'significant',
 'significantly',
 'similar',
 'similarly',
 'since',
 'sincere',
 'site',
 'six',
 'sixty',
 'sj',
 'sk',
 'sl',
 'slightly',
 'sm',
 'small',
 'smaller',
 'smallest',
 'sn',
 'so',
 'some',
 'somebody',
 'someday',
 'somehow',
 'someone',
 'somethan',
 'something',
 'sometime',
 'sometimes',
 'somewhat',
 'somewhere',
 'soon',
 'sorry',
 'specifically',
 'specified',
 'specify',
 'specifying',
 'sr',
 'st',
 'state',
 'states',
 'still',
 'stop',
 'strongly',
 'su',
 'sub',
 'substantially',
 'successfully',
 'such',
 'sufficiently',
 'suggest',
 'sup',
 'sure',
 'sv',
 'sy',
 'system',
 'sz',
 't',
 "t's",
 'take',
 'taken',
 'taking',
 'tc',
 'td',
 ...]

In [12]:
s = 'this. is: a string32 2 233?'
s = re.sub('[^\w\s]', '', s)
s

<>:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\Soheil\AppData\Local\Temp\ipykernel_9196\2287402470.py:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  s = re.sub('[^\w\s]', '', s)

'this is a string32 2 233'