In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import os

In [4]:
dataset = os.path.join('datasets', 'mydata.csv')
df = pd.read_csv(dataset)
df

   columns1 columns2 columns3
0         1        a        A
1         2        a        A
2         2        a        A
3         3        b        B
4         4        b        B
5         4        b        B

In [5]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [6]:
df.drop_duplicates()

   columns1 columns2 columns3
0         1        a        A
1         2        a        A
3         3        b        B
4         4        b        B

In [7]:
df.drop_duplicates(['columns2'])

   columns1 columns2 columns3
0         1        a        A
3         3        b        B